// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB0JttyZR-PsF6l-gboceTelPmssGqUig',
    appId: '1:29512331016:web:5f7ea1ca3821b001e346bd',
    messagingSenderId: '29512331016',
    projectId: 'intern-proj-fl',
    authDomain: 'intern-proj-fl.firebaseapp.com',
    storageBucket: 'intern-proj-fl.appspot.com',
    measurementId: 'G-07BM6686DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgMQS3nc2A5WmBVCgPiiHOVzCumjLNdyM',
    appId: '1:29512331016:android:d372c214ce83cac8e346bd',
    messagingSenderId: '29512331016',
    projectId: 'intern-proj-fl',
    storageBucket: 'intern-proj-fl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaAOZaOHvbWNkstL3HmJbCPzJ_KqN5ZDI',
    appId: '1:29512331016:ios:9af1ea2ce86d06c4e346bd',
    messagingSenderId: '29512331016',
    projectId: 'intern-proj-fl',
    storageBucket: 'intern-proj-fl.appspot.com',
    iosClientId: '29512331016-9l41q6uo4ab6acm74vcq97icbr2929um.apps.googleusercontent.com',
    iosBundleId: 'com.example.internProjFl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaAOZaOHvbWNkstL3HmJbCPzJ_KqN5ZDI',
    appId: '1:29512331016:ios:540dc208e8737500e346bd',
    messagingSenderId: '29512331016',
    projectId: 'intern-proj-fl',
    storageBucket: 'intern-proj-fl.appspot.com',
    iosClientId: '29512331016-ju1ic6sg5ig0seo37s6qed5l1283jb6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.internProjFl.RunnerTests',
  );
}
